server:
  port: 9999
  
spring:  datasource:    username: root
    password: root
    url: jdbc:mysql:///kongbuwu?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    
mybatis:  mapper-locations: classpath:mapper/*.xml  type-aliases-package: org.cskj.springbootStudent.bean
  
logging:  level:    org.cskj.springbootStudent.mapper: debug